### ISSUE TITLE
Add Headings to label rows of dice

### ISSUE THREAD

**Issue by VickiLanger** [ondras/rri#21]
### Issue
If one knows what the rows of dice are, they may easily figure out what they are. However, when I have introduced the game to new players, the two rows are confusing. 

### A Possible Change
I've dug around in the code, but I'm unsure exactly if or where you would want this changed. 

I'm imagining something like this could be added before instantiating the `pool` and `bonusPool` classes
```js
var poolHeading= document.createElement('h2');
   poolHeading.innerHTML = "Routes";
```
If it's matched up with style like this
```css
h2 {
font-size: inherit;
width: 64px;
}
```
it would look like this. 
![Screenshot 2023-05-12 at 14 09 59](https://github.com/ondras/rri/assets/46823403/3cd057af-2ba9-43f7-af6b-b7ad5eeecf24)
The pools would stay within the current width of the game

### An Actual Change?
If this is of interest, I'm happy to submit a pr. However, I am unsure where exactly those changes would need to be.
It seems the change could partially be made [here](https://github.com/ondras/rri/blob/07df8c0fada9e604fcde5570b36524b4d166b589/src/client/round.ts#LL20C11-L20C11) before the instantiating the pool class.

**Comment by ondras** [comment]
Hi @VickiLanger ,

thanks for the issue and your interest in Railroad Ink. I think that this is a useful change; we just need (exactly as you suggested) to limit the label's width - so it fits within the 524px limit of the game grid.

I am open to accepting a PR, but I can also make the change myself if you want. The `Pool` class's constructor shall ideally accept a string argument; this will be used to create the suggested `<h2>` element.

**Comment by VickiLanger** [comment]
I haven't worked with typescript before, and js isn't my forte either. Still, I'd like to give the change a shot. I appreciate your patience. 

Notes to Self
---
~~I'm in [pool.ts](https://github.com/VickiLanger/rri/blob/master/src/client/pool.ts), and I see a constructor for `BonusPool` but not for `Pool`.~~ I see, it's in `client.js`. Maybe not? `src/client/pool.ts` and `client/client.js` seem to contain the same classes. Surely, typescript doesn't require that you do the equivalent code in both, right? 

~~Initially, under `node: HTMLElement = html.node("div", {className:"pool"});` I tried creating a new `h2Node`, but I have found~~ I see now, the typescript syntax was throwing me off. It's `name: Type = whatever`

Goal: 
- ensure `Pool` has "Routes" in h2
- ensure `BonusPool` has "Special Routes" in h2
- fits within the width of game

Plan:
- style h2 element
- `Pool`
   - create an `<h2>` called `poolHeading` with the class `heading` and a parameter for the `headingText`
   - prepend heading to the beginning of the `node`
- `BonusPool`
   - add `bonus` to `classList` for `poolHeading`
   - send parameter for `headingText` to read "Special Routes"

When I was looking at `client/pool.ts` I was working on lines like: 
```ts
// under the creation of node
poolHeading: HTMLHeadingElement = html.node("h2", {className:"heading"}, "Routes");
node.prepend(poolHeading)

// in BonusPool constructor under other class addition to node
this.poolHeading.classList.add("bonus")
```

Question?
---
Before I change anything, I want to make sure I'm working in the right files. Should I be working in `src/client/pool.ts` and `src/css/app.less` || `client/client.js` and `client/client.css`?

**Comment by ondras** [comment]
Generally speaking, you should be working in `src/` ("src" = "source" = "the place where we do stuff"). In this case, `src/client/pool.ts`. Once you finish editing, you typically run `make` in the top-level directory; this invokes all the necessary build steps to convert ts->js and less->css and then bundle many .js files into one application file.

Running `make` can be only done when you have all build tools installed, though. We do that by running `npm i`, but that implies having `npm` installed... having the whole build chain set up properly can be a complex task. Feel free to only edit the source .ts file and create a Merge Request; I will do the building myself if necessary.

And now those changes. The `BonusPool` class is actually a lot simpler; you just change its constructor - instead of calling `super()`, it will do `super("Label for the bonus pool")`. This is because we want the `Pool` class constructor to accept a label value.

The `Pool` class has no constructor; we need to create one. We do that simply by adding

```js
constructor(label: string) {
  // create the <h2> here and append it to this.node
}
```

Finally, you need to search all places where a `new Pool()` instance is created and add an appropriate label (again, only in the `src/` subdirectory).

**Comment by VickiLanger** [comment]
I figured I should be working in the `src` directory, per usual. I figured there was something automated that converted and made the files for the browser to use. Thanks for the explanation. 

If it's alright with you, I'd like to pass on setting up a whole dev env for now. I shall have those changes done shortly.

**Comment by ondras** [comment]
MR merged, app re-built and published at https://ondras.github.io/rri/
